### ISSUE TITLE
Not launching activity

### ISSUE THREAD

**Issue by droidwithme** [rakshit444/news-sample-app#3]
2019-02-26 11:06:41.677 12633-12633/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: rakshitjain.news_sample_app, PID: 12633
    java.lang.RuntimeException: Unable to start activity ComponentInfo{rakshitjain.news_sample_app/com.rakshitjain.presentation.news.NewsActivity}: java.lang.IllegalArgumentException: Unable to create call adapter for io.reactivex.Flowable<com.rakshitjain.data.entities.NewsSourcesData>
        for method RemoteNewsApi.getNews
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: Unable to create call adapter for io.reactivex.Flowable<com.rakshitjain.data.entities.NewsSourcesData>
        for method RemoteNewsApi.getNews
        at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
        at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:237)
        at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:162)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy0.getNews(Unknown Source)
        at com.rakshitjain.data.repository.NewsRemoteImpl.getNews(NewsRemoteImpl.kt:14)
        at com.rakshitjain.data.repository.NewsRepositoryImpl.getNews(NewsRepositoryImpl.kt:20)
        at com.rakshitjain.domain.usecases.GetNewsUseCase.createFlowable(GetNewsUseCase.kt:17)
        at com.rakshitjain.domain.common.BaseFlowableUseCase.single(BaseFlowableUseCase.kt:10)
        at com.rakshitjain.domain.usecases.GetNewsUseCase.getNews(GetNewsUseCase.kt:22)
        at com.rakshitjain.presentation.news.NewsViewModel.fetchNews(NewsViewModel.kt:24)
        at com.rakshitjain.presentation.news.NewsActivity.onCreate(NewsActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:7036)
        at android.app.Activity.performCreate(Activity.java:7027)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        	... 9 more
     Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for io.reactivex.Flowable<com.rakshitjain.data.entities.NewsSourcesData>.
      Tried:
       * retrofit2.ExecutorCallAdapterFactory
        at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:241)
        at retrofit2.Retrofit.callAdapter(Retrofit.java:205)
        at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:235)
        	... 25 more

**Comment by rakshit444** [comment]
It's Fixed
